### PR TITLE
Status application automation

### PR DESCRIPTION
**Pull request by Stexinator**
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/133

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release

**Comment by moliloo** [comment]
I ll test it today

**Comment by moliloo** [comment]
- [x] [automatically apply status effects on self-cast](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/231ed4c9b3370e724a44ee4958fda87ba9625388)
- [x] [automatically apply status effects on apply damage](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/6ee2e3dba9bf4b8d43c157a33b973e4ac0769a0d)
- [ ] [automatically apply status effects to target of spells](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/9f2ccff285e96bef013681b2415dc4de3daa22ea)
- [x] [active effect name and img default to parent](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/761436074655c4abe573be0fa0dd4759bc92c52d)
- [x] [open verbal combat dialog when defending with counter-argue](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/2020e6ff581a0aa443fb28c767c040f5995c3a8f)
- [x] [don't apply active effects from unequipped items or deactivated global modifiers](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/c12a4492a56ae30322ff12b325a7a1cd0d2b1fd6) 
- [ ] [automatically apply global modifiers on hit](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/189c83aa59802edc2e9d501697d7f2188b9e51af)
- [x] [automatically apply global modifiers on damage](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/859d43ef9b077d2ff4370f6e167b49a803f24440)

**Comment by moliloo** [comment]
- [x] [automatically apply status effects to target of spells](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/9f2ccff285e96bef013681b2415dc4de3daa22ea)
- [x] [automatically apply global modifiers on hit](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/155/commits/189c83aa59802edc2e9d501697d7f2188b9e51af)

**Pull request merged**
