### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release

**Comment by Stexinator** [comment]
Anyone got progress already? I want to merge tomorrow

**Comment by moliloo** [comment]
I ll test today

**Comment by moliloo** [comment]
- [x] Carried Checkbox to Mounts,
      Even multiples mounts the sheet sum all of them;
- [x] Effect data and creation bugs,
      I belive is the data of item spell, works fine;
- [ ] Damage messages visibility
      Can you explain this to me? If its for the Public message, GM Blind options? If yes, it respect the type os message;
- [x] Add consume message for items
      I can use a consumable item by the Token Action Module, but if you add a feature to consume the item in the sheet i dont see where to use there

**Comment by Stexinator** [comment]
>     * [ ]  Damage messages visibility
>       Can you explain this to me? If its for the Public message, GM Blind options? If yes, it respect the type os message;
Yes that is it.

>     * [x]  Add consume message for items
>       I can use a consumable item by the Token Action Module, but if you add a feature to consume the item in the sheet i dont see where to use there

You can right click on items on the actor sheet

**Comment by moliloo** [comment]
> You can right click on items on the actor sheet

I try this before but doesn't show the context menu, i click between the inputs of the item, do i need to click in especific element of the item?

**Comment by Stexinator** [comment]
> > You can right click on items on the actor sheet
> 
> I try this before but doesn't show the context menu, i click between the inputs of the item, do i need to click in especific element of the item?

Nothing specific, but the item has to be configured as consumable. For this you need to open the configuration sheet of a valuable and click the specific checkbox

**Comment by moliloo** [comment]
Ok, i found the configuration, and its works now

Everything i tested is working now

**Pull request merged**
