### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at can you give me a rough timeline when you can test this?

**Comment by AlexanderTheGr3at** [comment]
I'll be doing it shortly

Thanks,
Alexander Hendry

-------- Original Message --------

**Comment by AlexanderTheGr3at** [comment]
- [ ] add roll button to clues : Error [localhost-1721928252389.log](https://github.com/user-attachments/files/16381640/localhost-1721928252389.log)
- [x] use another icon for hallucination 
- [x] show config symbol only when config available 
- [ ] add variable damage properties with dialog : Error [localhost-1721928587894.log](https://github.com/user-attachments/files/16381698/localhost-1721928587894.log)
- [x] enable effect functionality for armors again
- [x] removed athletics from melee skill group 
- [ ] allow users to drop items on diagrams : Not sure how to test this one, what's its purpose?
- [x] fix effects for items not working anymore 
- [x] fix localisation of weapon hands 
- [x] support status counter module : Although the counter doesn't seem to actually change at all

**Comment by Stexinator** [comment]
>     * [ ]  allow users to drop items on diagrams : Not sure how to test this one, what's its purpose?

Before only GMs could associate items to diagrams and formulas by dragging and dropping them

**Comment by AlexanderTheGr3at** [comment]
> > add variable damage properties with dialog : Error [localhost-1721928587894.log](https://github.com/user-attachments/files/16381698/localhost-1721928587894.log)
> 
> I need the character for this. You are missing a chunk of data here that I didnt expect

[fvtt-Actor-sir-engelnam-of-birchroot-RQNb3oZkC0qq8XKb.json](https://github.com/user-attachments/files/16382479/fvtt-Actor-sir-engelnam-of-birchroot-RQNb3oZkC0qq8XKb.json)
[fvtt-Actor-ivan-h9pbABJ5bdYQfmGc.json](https://github.com/user-attachments/files/16382480/fvtt-Actor-ivan-h9pbABJ5bdYQfmGc.json)
[fvtt-Actor-artemas-jqDRHdGk6VyBGB1W.json](https://github.com/user-attachments/files/16382481/fvtt-Actor-artemas-jqDRHdGk6VyBGB1W.json)

**Comment by AlexanderTheGr3at** [comment]
> > ```
> > * [ ]  allow users to drop items on diagrams : Not sure how to test this one, what's its purpose?
> > ```
> 
> Before only GMs could associate items to diagrams and formulas by dragging and dropping them

I still don't quite understand. What needs to be dragged/dropped onto a diagram for armour? Don't you just need to hit the little hammer button to craft it?

**Comment by Stexinator** [comment]
> > > ```
> > > * [ ]  allow users to drop items on diagrams : Not sure how to test this one, what's its purpose?
> > > ```
> > 
> > 
> > Before only GMs could associate items to diagrams and formulas by dragging and dropping them
> 
> I still don't quite understand. What needs to be dragged/dropped onto a diagram for armour? Don't you just need to hit the little hammer button to craft it?

When you open the diagram there is a field for associated items. This is the item that will be added when you do a real craft. Due to changes of the compendium all the original items were not found anymore and thus nothing is displayed. To fix it you need to drop the resulting item into the diagram again. Before the fix only GMs were allowed to do that. Now everyone can do that

**Comment by Stexinator** [comment]
> > > add variable damage properties with dialog : Error [localhost-1721928587894.log](https://github.com/user-attachments/files/16381698/localhost-1721928587894.log)
> > 
> > 
> > I need the character for this. You are missing a chunk of data here that I didnt expect
> 
> [fvtt-Actor-sir-engelnam-of-birchroot-RQNb3oZkC0qq8XKb.json](https://github.com/user-attachments/files/16382479/fvtt-Actor-sir-engelnam-of-birchroot-RQNb3oZkC0qq8XKb.json) [fvtt-Actor-ivan-h9pbABJ5bdYQfmGc.json](https://github.com/user-attachments/files/16382480/fvtt-Actor-ivan-h9pbABJ5bdYQfmGc.json) [fvtt-Actor-artemas-jqDRHdGk6VyBGB1W.json](https://github.com/user-attachments/files/16382481/fvtt-Actor-artemas-jqDRHdGk6VyBGB1W.json)

I tested some attacks and all were working without an issue. I need a detailed reproduction report to look further into it. Can you try to reload your game and check if it was just a migration issue?

**Comment by Stexinator** [comment]
@AlexanderTheGr3at both errors should be fixed now.

**Pull request merged**
