### PR TITLE
v12.2.0

### PR DESCRIPTION
**Pull request by Stexinator**
- fixed shield not working anymore
- added active effects to actor, global modifier and status effects
- some code refactoring (this touches creation of effects and global modifier)
- fixed Triggler not working

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release

**Comment by moliloo** [comment]
I will test today, but can you tell me where i can test the Triggler? I dont remember this feature before

**Comment by moliloo** [comment]
- [x] Fixed shield not working anymore
- [ ] Added active effects to actor, global modifier and status effects
     The active effects works well, but the global modifier doesn't save the inputs i do
- [ ] Fixed Triggler not working
     I dont see where i can test this change, can you explain to me?

**Comment by Stexinator** [comment]
>     I dont see where i can test this change, can you explain to me?

Triggler is part of the module ConditionLab & Triggler

**Comment by Stexinator** [comment]
> The active effects works well, but the global modifier doesn't save the inputs i do
Fixed, please test it again

**Comment by moliloo** [comment]
- [x] Fixed shield not working anymore
- [x] Added active effects to actor, global modifier and status effects
- [x] Fixed Triggler not working

@Stexinator i tested everything, its ready for merge

**Pull request merged**
