### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release

**Comment by moliloo** [comment]
This weekend i will be a little busy, but i believe ultil sunday i will give you the awnsers about my tests

**Comment by pedroaugustobt** [comment]
> @pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release

I'll test it in this weekend

**Comment by moliloo** [comment]
- [x] [fix sheet breaking on empty special in global modifier](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/149/commits/28bfae2cfafa8ea8fdf751040bf629e6161fda13)
- [x] [disable crit/fumble for stun and death saves](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/149/commits/9d40caf3d79a4de0a9ca11d4e9a5050081272910)
- [x] [fix buying from loot actor adding wrong amount](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/149/commits/0ce7aea3e6eef59d2dd1475d2e9a9a486ce8c0a9)
- [ ] [add location to damage spells](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/149/commits/cc957564cd6947e639af13d3074edcf9ef3e61b3)
Damage applies right, but the dialog to apply the damage, type of damage doesn't appears right
image
- [ ] [add meleeBonus option to monsters](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/149/commits/d85243bcc9997a1c9145b01da1f2289e527c4a65)
Meele Bonus appears in Monster Sheet, but it doesn't apply in damage

| Weapon In Monster Sheet | After Roll Damage in Monster Sheet |
|--------|--------|
| | image| 

- [x] [adding input for shield, luck and adrenaline in character sheet](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/149/commits/19cd75dd09f9ad8fd6daa04d659daa79a9092cb0)

**Comment by Stexinator** [comment]
> Meele Bonus appears in Monster Sheet, but it doesn't apply in damage
Cannot reproduce. Can you try againd and send me the actor?

**Comment by Stexinator** [comment]
> Damage applies right, but the dialog to apply the damage, type of damage doesn't appears right

This is a problem that you can also see on the current live version. So it was not introduced with this feature. I set it to elemental for now. Can you create an issue to display the proper type?

**Comment by moliloo** [comment]
> Cannot reproduce. Can you try again and send me the actor?

I create a monster sheet, the i copy a exact weapon wich works in character sheet to monster sheet, i just set the stats after that, i try it again e nothing happen
[Monster-meele-bonus-test.json](https://github.com/user-attachments/files/17196780/fvtt-Actor-monster-meele-bonus-test-t4dGylPO5PbGnRSW.json)

> This is a problem that you can also see on the current live version. So it was not introduced with this feature. I set it to elemental for now. Can you create an issue to display the proper type?

Ok, i'll do that

**Comment by Stexinator** [comment]
> I create a monster sheet, the i copy a exact weapon wich works in character sheet to monster sheet, i just set the stats after that, i try it again e nothing happen

Did you activate it in the monster settings?

**Comment by moliloo** [comment]
> Did you activate it in the monster settings?

My bad @Stexinator, i forget about this setting, i tested it again and the feature works, ty 👍

- [x] add location to damage spells
- [x] add meleeBonus option to monsters

All features are tested now

**Pull request merged**
