### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/208
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/207
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/202
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/176

### CODE REVIEW

**Comment by taragor** [comment]
I dont beleive this by itself will fix #208. The modifiers are created in module/actor/sheets/mixins/skillModifierMixin.js Line 9:

```javascript
newModifierList.push({ name: 'Modifier', value: 0 });

this.actor.update({
    [`system.skills.${this.skillMap[skill].attribute.name}.${skill}.modifiers`]: newModifierList
});
``` 
 as anonymous object

 rather than using the function modifier fixed in module/data/actor/templates/common/modifierData.js

**Comment by Stexinator** [comment]
It applies the schema and sees that no ``id`` was supplied so it checks for the default which will apply a random id. This is already used in a lot of other modifiers without problem

**Comment by taragor** [comment]
I see. Thanks for the explanation

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release
@taragor I am always in need of testers. If you want you can test too

**Comment by taragor** [comment]
Sure, i can try to test. Is there an easy way to switch my world to the dev branch?

**Comment by Stexinator** [comment]
Unfortunately not. Foundry does not support beta or test builds. I wrote https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/wiki/Beta%E2%80%90Testing-a-feature if that is not enough info, hit me up

**Comment by taragor** [comment]
I've done some testing and can confirm that the modifiers work as expected

**Pull request merged**
