### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ortegamarcel**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release. 

I would like to release it tomorrow :)

**Comment by AlexanderTheGr3at** [comment]
I'll test this evening.

**Comment by AlexanderTheGr3at** [comment]
- [x] fix incoming instead of modified damage applied to actor 
- [x] Feature/context menu defense verbal combat
- [x] add configuration sheet for valuables - consumable
- [x] added source book field to items 
- [ ] monsters can configure tailWing - Needs Fixing
- [x] decouple global modifier from hard coded compendium

**Comment by Stexinator** [comment]
@AlexanderTheGr3at tailWing can be tested again :)

**Comment by ortegamarcel** [comment]
Please add some points about what was done in the description. So that it can be used to write the release notes later.

**Comment by AlexanderTheGr3at** [comment]
Everything is working great now

**Pull request merged**
