### PR TITLE
v12.5.0

### PR DESCRIPTION
**Pull request by Stexinator**
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/230
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/225
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/237
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/232

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at @taragor this is ready for testing

**Comment by Stexinator** [comment]
This will be merged coming sunday.

**Comment by moliloo** [comment]
- [x] [show rolled location in damage chat message](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/84ab2597d495d6b6cb9ba04fd6d2f88828897ee7)
- [x] [fix effects duplication on weapon attack](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/f39d52a334751717618f3d4d9aed1bbb9c3ae33d)
- [x] [improve localisation of used hands for weapons](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/a2ec023f3618d2f0bb22b52df61445668f87a05f)
- [x] [fix deprecations in enhancement sheet](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/e62292971f772d8faafa6ea2a52e47812b909288)
- [x] [Introducing Repair system](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/ce3067d1e65abc190907a5f9f7104ca9c4368e05)
- [x] [New feature - GM craft](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/32986e39c2186197ce4009269b4928093e7d93bd)
- [ ] [Compendium lookup for a missing components](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/94449704e72c1735d4ff91e4ff5ac8a0930de624)
- [x] [fix magical gift not rolling](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/c0de993507db18785b36172b5cc4cc6689cba55f)
- [ ] [refactor region macro creation and add more behaviours](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/8063aadf516779234fa2f9ac1cae294a3e6e4afb)
- [ ] [add new way to configure custom hp/sta/resolve](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/1f7493f1bbe93f5a106a542a55d3bc68528c6ff0)
- [x] [Migrating repair dialog to Applicationv2](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/7cbbda11427defd4565df1ab4e683b7dec042443)
- [ ] [refactor socialStanding + add optional threshold to skillchecks](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/2c25ced2fee299a02de7265dbd5d28588240c7d9)
- [ ] [add rollData to created regions](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/f186595ec6ccb693808ed6640ddec51b35ab621d)
- [ ] [style background section and fix hover style for active effects section](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/c47641c6d829059c8b176b128846bc0e7025d1f2)
- [x] [rework actor dialogs to V2 (no mixins)](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/ce1d1c5b775287fa760a9dbb0d2d95508bfda3a6)

**Comment by moliloo** [comment]
- [x] [add tokenPreMove to regions, enforce UUIDs in macro fields](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/234/commits/643e112d2a9846f82e4cb43fbd10e033392299cf)

**Pull request merged**
