### PR TITLE
reworked fixes (lang de)

### PR DESCRIPTION
**Pull request by LinkDragmire**
Added second translation for swordmanship, added types

Rework latest bugs

### CODE REVIEW

**Review by Stexinator — CHANGES_REQUESTED** [review]
Whitespace issue

**Comment by LinkDragmire** [comment]
> Whitespace issue

can't see the error

**Comment by Stexinator** [comment]
You changed 2320 lines (removed 1153, added 1167) and most of these are just whitespace changes

**Comment by Stexinator** [comment]
You should also work from dev and not main to see the current status.
You are also removing the activeEffect block

**Comment by LinkDragmire** [comment]
Regarding the whitespaces, yes. My Development Software converts this to clean using of Tabs not a lune wof whitespaces

**Comment by LinkDragmire** [comment]
added all changes

**Review by Stexinator — APPROVED** [review]

**Pull request merged**
