### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/217
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/210
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/180
closes https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/issues/223

### CODE REVIEW

**Comment by Stexinator** [comment]
Additionally everything casting spells (not the results, just until the dialog opens) need to be tested

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at @taragor this is ready for testing

**Comment by pedroaugustobt** [comment]
- [x] fix deprecations of race sheet
- [x] add "all skills" skill group
- [x] fix meleeBonus warning for non-linked actors
- [x] improve macro hotbar creation
- [x] fix ptbr lang
- [x] fix displaying weapon effects and hands
- [ ] refactor casting spell
Refactoring is working, but template and region are not being placed on canvas
image

**Comment by pedroaugustobt** [comment]
Another thing, test the Sterilizing Fluid again to see if it was removing 2 days max from the critical wound, but it only adds 1 day

https://github.com/user-attachments/assets/d33318ac-d1b7-484c-b4a6-b7be821ceede

**Comment by Stexinator** [comment]
> Refactoring is working, but template and region are not being placed on canvas

Cannot reproduce. Can you send me your actor?

**Comment by pedroaugustobt** [comment]
> > The code I use makes it so that at the time of complete rest, if the user uses the sterilizing fluid, two days maximum of the critical wound will be removed.
> 
> This would be applied on every day resting with sterilizing fluid. There is a bigger problem with automating that. Can you open a bug for it? I need to adjust the object data so that it works as intended

Ok

**Pull request merged**
