### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Stexinator**

### CODE REVIEW

**Comment by Stexinator** [comment]
@pedroaugustobt @moliloo @AlexanderTheGr3at this is ready for release

**Comment by Stexinator** [comment]
Anyone can give an ETA when you will have tested it?

**Comment by moliloo** [comment]
@Stexinator For me in 3 weeks, when i ll be back tô home

**Comment by Stexinator** [comment]
@pedroaugustobt @AlexanderTheGr3at any idea?

**Comment by AlexanderTheGr3at** [comment]
Shit, that's my bad. Thought I wasn't needed anymore since so many people are contributing aha. I'll test it today!

**Comment by moliloo** [comment]
- [ ] [add remove enhancement functionality](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/127/commits/f5839ec344f06fe8995c787073e42320a48d763e)
The functionality works has intended only if the sheet has one rune, but when have more quantity, the functionality shows a problem: Deleted all amount when equip and rune, when remove the rune, the quantity backs to one. The same occurs with other enhancements types 

| Before Apply Rune  | Rune in Armor  | After Remove Rune |
|--------|--------|--------|
|  |  |  |

- [ ] [add parrying property to weapons](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/127/commits/3aa66a598a5e9498c7a30ed7080bf284b4c883e1)
I cannot test this because a error in console appears when i select `Parry` or `Parry Throw Weapon` in defense button in actor sheet or in context menu from weapon hit card

   
   
- [ ] [damage that bypasses armor does not damage SP](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/127/commits/5dc2138ca185bfc9e16d28c91556a9137ae8b13c)
I configure the weapons and only the option `Bypasses Natural Armor` doesnt damage SP, can you explain the diference between the `Bypasses Natural Armor` and `Bypasses Worn Armor`? Then i can teste better this feature

- [x] [round SP up after improved armor piercing](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/127/commits/7a60703b1dfd101f028bdb2a2108468e50c73989)
- [x] [add active effects to armor config](https://github.com/witchertrpg-foundryvtt/TheWitcherTRPG/pull/127/commits/c49daa73b6ace524df06eb6ce05d96b4bd782bb9)

#### Adicional Notes
@Stexinator i added this section to show a console warning isn't specific about the commits above, but i think is good let you know.
- Warning: When open and edit come field in the enhancement item, in console log appears this warning

**Comment by Stexinator** [comment]
>I cannot test this because a error in console appears when i select Parry or Parry Throw Weapon in defense button in actor sheet or in context menu from weapon hit card

fixed

**Comment by Stexinator** [comment]
>I configure the weapons and only the option Bypasses Natural Armor doesnt damage SP, can you explain the diference between the Bypasses Natural Armor and Bypasses Worn Armor? Then i can teste better this feature

This was the wrong way. Natural armor is never reduced. When bypassing normal armor, the normal armor (light, medium, heavy) should not be reduced too. There should be no interaction with bypassing natural armor

**Comment by Stexinator** [comment]
> The functionality works has intended only if the sheet has one rune, but when have more quantity, the functionality shows a problem: Deleted all amount when equip and rune, when remove the rune, the quantity backs to one. The same occurs with other enhancements types

Fixed

**Comment by pedroaugustobt** [comment]
@Stexinator I tested everything today, and it's working. Some adjustments to the layout need to be implemented. Now I'm getting back to the project, sorry for the time away, I had some projects on priority

**Pull request merged**
